# Generated by Django 2.2.6 on 2019-11-04 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostOrderRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickupPointType', models.CharField(choices=[('Shop', 'Shop'), ('Home', 'Home'), ('Office', 'Office'), ('Inperson', 'Inperson')], max_length=50)),
                ('pickupPoint', models.CharField(choices=[('Khagan', 'Khagan'), ('Charabag', 'Charabag'), ('Savar', 'Savar'), ('Mirpir-1', 'Mirpur-1'), ('New Market', 'New Market'), ('Nilkhet', 'Nilkhet'), ('Panthopath', 'Panthopath'), ('Shahbagh', 'Shahbagh'), ('Gulistan', 'Gulistan'), ('Uttara', 'Uttara'), ('Airport', 'Airport'), ('Dhanmondi', 'Dhanmondi'), ('Shyamoli', 'Shyamoli')], max_length=105)),
                ('pickupPointDescription', models.CharField(max_length=2055)),
                ('deliveryPoint', models.CharField(choices=[('YKSG East', 'YKSG East'), ('YKSG West', 'YKSG West'), ('YKSG New Buliding', 'YKSG New Building'), ('YKSG Extension 1', 'YKSG Extension 1')], max_length=255)),
                ('parcelType', models.CharField(choices=[('Documents', 'Documents'), ('Medicine', 'Medicine'), ('Electronics', 'Electronics'), ('Books', 'Books'), ('Clothes', 'Clothes'), ('Food', 'Food'), ('Accessories', 'Accessories'), ('Others', 'Others')], max_length=255)),
                ('parcelDescription', models.CharField(max_length=2055)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=4)),
                ('deliveryDate', models.DateField(help_text="Format: '%Y-%m-%d' i.e. 2006-10-25")),
                ('postDate', models.DateTimeField()),
                ('accepted', models.BooleanField(default=False)),
                ('deliveryCost', models.IntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.ProfileEdit')),
            ],
        ),
    ]
