# Generated by Django 2.2.6 on 2019-11-04 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordertrack', '0002_auto_20191104_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postorderrequest',
            name='pickupPoint',
            field=models.CharField(choices=[('Khagan', 'Khagan'), ('Charabag', 'Charabag'), ('Savar', 'Savar'), ('Mirpir-1', 'Mirpur-1'), ('New Market', 'New Market'), ('Nilkhet', 'Nilkhet'), ('Panthopath', 'Panthopath'), ('Shahbagh', 'Shahbagh'), ('Gulistan', 'Gulistan'), ('Uttara', 'Uttara'), ('Airport', 'Airport'), ('Dhanmondi', 'Dhanmondi'), ('Shyamoli', 'Shyamoli'), ('IDB', 'IDB')], max_length=105),
        ),
    ]
